name: Android Deploy to Yandex Cloud

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build Release APK
        run: ./gradlew assembleRelease

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-access-key-id: ${{ secrets.YC_ACCESS_KEY }}
#          aws-secret-access-key: ${{ secrets.YC_SECRET_KEY }}
#          aws-region: ru-central1

      - name: Create local.properties
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" > local.properties
          echo "UPDATE_URL=${{ secrets.UPDATE_URL }}" >> local.properties

      - name: Deploy to storage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YC_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_KEY }}
          AWS_DEFAULT_REGION: ru-central1
        run: |
          
          VERSION_NAME=$(echo ${GITHUB_REF#refs/tags/v})
          
          APK_URL="https://${{ secrets.YC_BUCKET_NAME }}.storage.yandexcloud.net/app.apk"
          
          COMMIT_MSG=$(git log -1 --pretty=%B)
          CLEAN_MSG=$(echo "$COMMIT_MSG" | tr -d '"' | tr '\n' ' ')
          
          echo "{\"newVersionCode\": \"$VERSION_NAME\", \"apkUrl\": \"$APK_URL\", \"releaseNotes\": \"$CLEAN_MSG\"}" > version.json
          
          aws s3 cp version.json s3://${{ secrets.YC_BUCKET_NAME }}/version.json \
            --endpoint-url=https://yandexcloud.net
          
          aws s3 cp app/build/outputs/apk/release/app-release.apk s3://${{ secrets.YC_BUCKET_NAME }}/app.apk \
            --endpoint-url=https://yandexcloud.net